/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/styles/**/*.{css}",
    "./src/assets/**/*.{css,scss}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        secondary: {
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
        },
        cream: 'var(--samplip-cream)',
        darkcream:'var(--samplip-dark-cream)',
        deilcut:'var(--samplip-deil-cut)',
        grain:'var(--samplip-grain)',
        strawberry:'var(--samplip-strawberry)',
        facebookBlue:'var(--facebook-blue)',
        instagramBlack:'var(--instagram-black)',
        youtubeRed:'var(--youtube-red)',
        scallion:'var(--scallion)',
        cucumber:'var(--cucumber)',
        grilledMeats:'var(--grilled-meats)',
        samlipRed:'var(--samlip-red)',
        line2:'var(--line2)',
        grayTxt:'var(--gray_txt)',
        grayBack:'var(--gray_back)',
        color:'var(--color)',
        orange:'var(--orange)',
        hazelnut:'var(--hazelnut)',
        surface:{
          0: 'var(--surface-0)',
          50: 'var(--surface-50)',
          100: 'var(--surface-100)',
          200: 'var(--surface-200)',
          300: 'var(--surface-300)',
          400: 'var(--surface-400)',
          500: 'var(--surface-500)',
        },
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
        'span-17': 'span 17 / span 17',
        'span-18': 'span 18 / span 18',
        'span-19': 'span 19 / span 19',
        'span-20': 'span 20 / span 20',
        'span-21': 'span 21 / span 21',
        'span-22': 'span 22 / span 22',
        'span-23': 'span 23 / span 23',
        'span-24': 'span 24 / span 24',
      },
    },
  },
  plugins: [],
};
